### ISSUE TITLE
Consider defining a bean of type 'cn.usr.service.UsrcloudMqttCallback' in your configuration. 请问下，这是什么问题，我的springboot是1.5.4的

### ISSUE THREAD

**Issue by itzj86** [cuisongliu/usrcloud-boot-starter#2]
Description:

Field usrcloudMqttCallback in com.cuisongliu.usrcloud.autoconfig.UsrcloudAutoConfig required a bean of type 'cn.usr.service.UsrcloudMqttCallback' that could not be found.

Action:

Consider defining a bean of type 'cn.usr.service.UsrcloudMqttCallback' in your configuration.

**Comment by cuisongliu** [comment]
请在自己的项目上 声明一个Bean (```@Service``` 注解声明 )继承自 UsrcloudMqttCallback  看错误信息是没有声明一个继承自 UsrcloudMqttCallback 的一个回调函数

**Comment by itzj86** [comment]
@Service
public class UsrCloudCallback extends UsrCloudMqttCallbackAdapter
 代码提示没有UsrcloudMqttCallback 这个类了。是继承了上面的UsrCloudMqttCallbackAdapter 这个类。启动还是报同样的错

**Comment by cuisongliu** [comment]
UsrcloudMqttCallback 只要你在自己的项目是要继承这个类 
UsrCloudMqttCallbackAdapter这个类我已经去掉了 没有这个类 不需要继承的

**Comment by itzj86** [comment]
![_20180407162730](https://user-images.githubusercontent.com/5669477/38452962-a758ace0-3a80-11e8-85ad-e8386b50364e.png)
![_20180407162833](https://user-images.githubusercontent.com/5669477/38452967-c0682c38-3a80-11e8-88fa-f0eba5acf1f5.png)
我看了依赖的，里面是有你是说的那个类。但是不知道为什么就是import不了

**Comment by cuisongliu** [comment]
你看看你依赖的版本号是多少 是1.4.1么？

**Comment by itzj86** [comment]
<dependency>
		   <groupId>com.cuisongliu</groupId> 
		   <artifactId>usrcloud-spring-boot-starter</artifactId>
		   <version>1.4.1</version>
		 </dependency>

**Comment by cuisongliu** [comment]
刚看到 UsrcloudMqttCallback 是个借口 你得实现所有的方法。应该是你没实现的缘故 不能extends 应该是implements

**Comment by itzj86** [comment]
ok 已经可以使用了。非常感谢
