### ISSUE TITLE
如何在UsrcloudMqttCallback 里面使用UsrcloudMqttClien（采用注入的方式）

### ISSUE THREAD

**Issue by char1st** [cuisongliu/usrcloud-boot-starter#3]
或者能不能添加一个不带callback的MqttClien？

**Comment by cuisongliu** [comment]
什么样的应用场景？不需要回调函数么？

**Comment by cuisongliu** [comment]
UsrcloudMqttCallback 中调用UsrcloudMqttClien 在MQTT的处理机制中来讲应该是不行的，因为这样的话相当于循环依赖了。UsrcloudMqttClien 设置了callback方法,但是你要callback中去调用UsrcloudMqttClien相当于循环了。

**Comment by char1st** [comment]
场景是这样的 
我想在收到DTU设备的透传的数据后（onReceiveEvent），再publish数据到DTU设备.
有没有更好的方式么？
如果不行的话 ，只能把 publish做成另外一个服务 ，在onReceiveEvent 中调用这个服务。

**Comment by cuisongliu** [comment]
之前我试过如果用线程跑你的这个方法是可以的，但是调试不太好调试. 回头我想想怎么解决这个问题。

**Comment by mylzj** [comment]
请问上述问题有没有好的解决方法呢，我现在也是想在收到数据的回调函数调用发布函数，这样子也不行，请问有没有解决方法呢

**Comment by char1st** [comment]
用@lazy

```java
@Lazy
@Autowired
private UsrcloudMqttClient usrcloudMqttClient;
```

**Comment by mylzj** [comment]
十分谢谢！起作用了
